id: I14CCDC2C
legacy_id: P009544
ocr_import_info:
  bdrc_scan_id: W1KG18586
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T22:58:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:51:12.857523+00:00'
last_modified: 2022-08-31 18:09:02.098237
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18586
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18586
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཏུན་ཧོང་ནས་ཐོན་པའི་བོད་ཀྱི་ཡིག་ཆ་ཁག་ཅིག
  author: pelliot, paul
statistics:
  ocr_word_mean_confidence_index: 0.7968499032776892
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG18743:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18743
      total_pages: 1242
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG18743.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8279666423822377
    legacy_id: v004
  I1KG18740:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18740
      total_pages: 338
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18740.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.5368357264367456
    legacy_id: v001
  I1KG18742:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18742
      total_pages: 1096
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG18742.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8155756491535097
    legacy_id: v003
  I1KG18741:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18741
      total_pages: 374
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG18741.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.610922179085896
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
