id: I14CCDC2C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:07:42+00:00'
last_modified: '2022-06-08T11:47:01.315081+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18586
  title: ཏུན་ཧོང་ནས་ཐོན་པའི་བོད་ཀྱི་ཡིག་ཆ་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2FD5:
      image_group_id: I1KG18740
      title: ''
      total_pages: 338
      order: 1
      base_file: 2FD5.txt
    77DC:
      image_group_id: I1KG18741
      title: ''
      total_pages: 374
      order: 2
      base_file: 77DC.txt
    0872:
      image_group_id: I1KG18742
      title: ''
      total_pages: 1096
      order: 3
      base_file: 0872.txt
    262D:
      image_group_id: I1KG18743
      title: ''
      total_pages: 1242
      order: 4
      base_file: 262D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
